// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: internal/protos/v1/breakeven/breakeven.proto

package breakeven

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BreakevenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseValue              int64   `protobuf:"varint,1,opt,name=houseValue,proto3" json:"houseValue,omitempty"`
	DownPayment             float32 `protobuf:"fixed32,2,opt,name=downPayment,proto3" json:"downPayment,omitempty"`
	PropertyTaxRate         float32 `protobuf:"fixed32,3,opt,name=propertyTaxRate,proto3" json:"propertyTaxRate,omitempty"`
	PropertyTransferTaxRate float32 `protobuf:"fixed32,4,opt,name=propertyTransferTaxRate,proto3" json:"propertyTransferTaxRate,omitempty"`
	LivingYears             int32   `protobuf:"varint,5,opt,name=livingYears,proto3" json:"livingYears,omitempty"`
	MortgageInterestRate    int32   `protobuf:"varint,6,opt,name=mortgageInterestRate,proto3" json:"mortgageInterestRate,omitempty"`
	MortgageTerm            int32   `protobuf:"varint,7,opt,name=mortgageTerm,proto3" json:"mortgageTerm,omitempty"`
	MonthlyCommonCost       int32   `protobuf:"varint,8,opt,name=monthlyCommonCost,proto3" json:"monthlyCommonCost,omitempty"`
}

func (x *BreakevenRequest) Reset() {
	*x = BreakevenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_v1_breakeven_breakeven_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreakevenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakevenRequest) ProtoMessage() {}

func (x *BreakevenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_v1_breakeven_breakeven_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakevenRequest.ProtoReflect.Descriptor instead.
func (*BreakevenRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_v1_breakeven_breakeven_proto_rawDescGZIP(), []int{0}
}

func (x *BreakevenRequest) GetHouseValue() int64 {
	if x != nil {
		return x.HouseValue
	}
	return 0
}

func (x *BreakevenRequest) GetDownPayment() float32 {
	if x != nil {
		return x.DownPayment
	}
	return 0
}

func (x *BreakevenRequest) GetPropertyTaxRate() float32 {
	if x != nil {
		return x.PropertyTaxRate
	}
	return 0
}

func (x *BreakevenRequest) GetPropertyTransferTaxRate() float32 {
	if x != nil {
		return x.PropertyTransferTaxRate
	}
	return 0
}

func (x *BreakevenRequest) GetLivingYears() int32 {
	if x != nil {
		return x.LivingYears
	}
	return 0
}

func (x *BreakevenRequest) GetMortgageInterestRate() int32 {
	if x != nil {
		return x.MortgageInterestRate
	}
	return 0
}

func (x *BreakevenRequest) GetMortgageTerm() int32 {
	if x != nil {
		return x.MortgageTerm
	}
	return 0
}

func (x *BreakevenRequest) GetMonthlyCommonCost() int32 {
	if x != nil {
		return x.MonthlyCommonCost
	}
	return 0
}

type BreakevenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *BreakevenResponse) Reset() {
	*x = BreakevenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_v1_breakeven_breakeven_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreakevenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakevenResponse) ProtoMessage() {}

func (x *BreakevenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_v1_breakeven_breakeven_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakevenResponse.ProtoReflect.Descriptor instead.
func (*BreakevenResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_v1_breakeven_breakeven_proto_rawDescGZIP(), []int{1}
}

func (x *BreakevenResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_internal_protos_v1_breakeven_breakeven_proto protoreflect.FileDescriptor

var file_internal_protos_v1_breakeven_breakeven_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x2f, 0x62,
	0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x76, 0x31, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x22, 0xe0, 0x02, 0x0a,
	0x10, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54,
	0x61, 0x78, 0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x61, 0x78, 0x52, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a,
	0x17, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x54, 0x61, 0x78, 0x52, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x17,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x54, 0x61, 0x78, 0x52, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x69, 0x76, 0x69, 0x6e,
	0x67, 0x59, 0x65, 0x61, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x69,
	0x76, 0x69, 0x6e, 0x67, 0x59, 0x65, 0x61, 0x72, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x6d, 0x6f, 0x72,
	0x74, 0x67, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x54, 0x65, 0x72,
	0x6d, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x6f,
	0x6e, 0x74, 0x68, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x73, 0x74, 0x22,
	0x2f, 0x0a, 0x11, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x66, 0x0a, 0x10, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x43, 0x61, 0x6c, 0x63, 0x42, 0x72, 0x65, 0x61,
	0x6b, 0x65, 0x76, 0x65, 0x6e, 0x12, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x6b,
	0x65, 0x76, 0x65, 0x6e, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x6b,
	0x65, 0x76, 0x65, 0x6e, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x62,
	0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_v1_breakeven_breakeven_proto_rawDescOnce sync.Once
	file_internal_protos_v1_breakeven_breakeven_proto_rawDescData = file_internal_protos_v1_breakeven_breakeven_proto_rawDesc
)

func file_internal_protos_v1_breakeven_breakeven_proto_rawDescGZIP() []byte {
	file_internal_protos_v1_breakeven_breakeven_proto_rawDescOnce.Do(func() {
		file_internal_protos_v1_breakeven_breakeven_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_v1_breakeven_breakeven_proto_rawDescData)
	})
	return file_internal_protos_v1_breakeven_breakeven_proto_rawDescData
}

var file_internal_protos_v1_breakeven_breakeven_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protos_v1_breakeven_breakeven_proto_goTypes = []interface{}{
	(*BreakevenRequest)(nil),  // 0: v1.breakeven.BreakevenRequest
	(*BreakevenResponse)(nil), // 1: v1.breakeven.BreakevenResponse
}
var file_internal_protos_v1_breakeven_breakeven_proto_depIdxs = []int32{
	0, // 0: v1.breakeven.BreakevenService.CalcBreakeven:input_type -> v1.breakeven.BreakevenRequest
	1, // 1: v1.breakeven.BreakevenService.CalcBreakeven:output_type -> v1.breakeven.BreakevenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protos_v1_breakeven_breakeven_proto_init() }
func file_internal_protos_v1_breakeven_breakeven_proto_init() {
	if File_internal_protos_v1_breakeven_breakeven_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_v1_breakeven_breakeven_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreakevenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_v1_breakeven_breakeven_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreakevenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_v1_breakeven_breakeven_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_v1_breakeven_breakeven_proto_goTypes,
		DependencyIndexes: file_internal_protos_v1_breakeven_breakeven_proto_depIdxs,
		MessageInfos:      file_internal_protos_v1_breakeven_breakeven_proto_msgTypes,
	}.Build()
	File_internal_protos_v1_breakeven_breakeven_proto = out.File
	file_internal_protos_v1_breakeven_breakeven_proto_rawDesc = nil
	file_internal_protos_v1_breakeven_breakeven_proto_goTypes = nil
	file_internal_protos_v1_breakeven_breakeven_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BreakevenServiceClient is the client API for BreakevenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BreakevenServiceClient interface {
	CalcBreakeven(ctx context.Context, in *BreakevenRequest, opts ...grpc.CallOption) (*BreakevenResponse, error)
}

type breakevenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBreakevenServiceClient(cc grpc.ClientConnInterface) BreakevenServiceClient {
	return &breakevenServiceClient{cc}
}

func (c *breakevenServiceClient) CalcBreakeven(ctx context.Context, in *BreakevenRequest, opts ...grpc.CallOption) (*BreakevenResponse, error) {
	out := new(BreakevenResponse)
	err := c.cc.Invoke(ctx, "/v1.breakeven.BreakevenService/CalcBreakeven", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreakevenServiceServer is the server API for BreakevenService service.
type BreakevenServiceServer interface {
	CalcBreakeven(context.Context, *BreakevenRequest) (*BreakevenResponse, error)
}

// UnimplementedBreakevenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBreakevenServiceServer struct {
}

func (*UnimplementedBreakevenServiceServer) CalcBreakeven(context.Context, *BreakevenRequest) (*BreakevenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcBreakeven not implemented")
}

func RegisterBreakevenServiceServer(s *grpc.Server, srv BreakevenServiceServer) {
	s.RegisterService(&_BreakevenService_serviceDesc, srv)
}

func _BreakevenService_CalcBreakeven_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreakevenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakevenServiceServer).CalcBreakeven(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.breakeven.BreakevenService/CalcBreakeven",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakevenServiceServer).CalcBreakeven(ctx, req.(*BreakevenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BreakevenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.breakeven.BreakevenService",
	HandlerType: (*BreakevenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalcBreakeven",
			Handler:    _BreakevenService_CalcBreakeven_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/protos/v1/breakeven/breakeven.proto",
}
